# Generated by Django 5.1.1 on 2024-09-18 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_favoriteuserbook_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriteuserbook',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.book'),
        ),
    ]
